<template>
  <hw-carousel
    height="200px"
    :autoplay="true"
    :loop="true"
    :initial-index="0"
    :interval="3000"
  >
    <hw-carousel-item></hw-carousel-item>
    <hw-carousel-item></hw-carousel-item>
  </hw-carousel>
</template>
